[package]
name = "weave"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "weave"
path = "src/main.rs"

[lib]
name = "weave"
path = "src/lib.rs"

[dependencies]
bytes = { workspace = true }
clap = { workspace = true }
ed25519-dalek = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
weaver-mux = { workspace = true }
weaver-proto = { workspace = true }
weaver-tokio = { workspace = true }
